apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:15.1
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "kubenesuser"
          - name: POSTGRES_DB
            value: "kubenewsdb"
          - name: POSTGRES_PASSWORD
            value: "kubenews2023"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: juliasantos/kube-news:v1
        ports:
          - containerPort: 8080
        env:
          - name: DB_USERNAME
            value: "kubenesuser"
          - name: DB_DATABASE
            value: "kubenewsdb"
          - name: DB_PASSWORD
            value: "kubenews2023"
          - name: DB_HOST
            value: "postgre"
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer